Shib & Cas Authentification method
correctexam/corrigeExamBack pull request #58
Opened 2023-04-07 08:52 UTC by Barbapapou

Authentication par Cas et Shibboleth dans le cadre de l'intégration de CorrectExam au sein de la DSI.

2023-04-25 11:56 UTC, barais requested changes

2023-04-25 11:56 UTC, barais commented on src/main/docker/Dockerfile.build.amd64
These changes must not be in the pull request

2023-04-25 11:56 UTC, barais commented on src/main/docker/Dockerfile.front
These changes must not be in the pull request

2023-04-25 11:56 UTC, barais commented on src/main/docker/app.yml
These changes must not be in the pull request

2023-04-25 11:56 UTC, barais commented on src/main/docker/app.yml
These changes must not be in the pull request

2023-04-25 11:56 UTC, barais commented on src/main/resources/application.properties
> +configcas.server_cas = https://sso-cas6-test.univ-rennes1.fr
Does it mean that if this key are absent, we go back to a standard authentification ?

2023-04-25 11:56 UTC, barais commented on src/main/docker/Dockerfile.front
Keep the default url in dockerfile

2023-04-25 11:56 UTC, barais commented on src/main/docker/app.yml
do not touch the app.yml in your PR

2023-04-25 11:56 UTC, barais commented on src/main/docker/exampleconf/exam.conf
Do not force a specific https on localhost

2023-04-25 11:56 UTC, barais commented on src/main/resources/config/liquibase/changelog/20220719165535_update_entity_StudentResponse.xml
why did you remove this

2023-04-25 11:56 UTC, barais commented on src/main/resources/config/liquibase/changelog/20220824165535_update_entity_Question.xml
why did you remove this

2023-05-22 08:07 UTC, Barbapapou commented on src/main/resources/application.properties
> +configcas.server_cas = https://sso-cas6-test.univ-rennes1.fr
CAS authentication is simply reached from another endpoint. The usual way of authentication is still available regardless of the state of this key.

2023-05-22 08:10 UTC, Barbapapou commented on src/main/resources/config/liquibase/changelog/20220719165535_update_entity_StudentResponse.xml
While attempting to set up a MySQL database, I encountered error messages indicating that this option is not available. This doesn't change the effect of the migration.

2023-05-22 08:22 UTC, Barbapapou commented
The requested changes have been made.

2023-05-23 09:16 UTC, merged